### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by zeenix** [Enet4/byteordered#13]
Hi, 

This crate looks like exactly what we need in zbus but looks like this maybe unmaintained. @Enet4 could you please let me know about the status?

**Comment by Enet4** [comment]
Hello! If there is something specific that I can do to make it seem more reliable, feel free to let me know.

For what it's worth, this project is a small component that hasn't required a lot of maintenance. It is also used by other active projects of mine.

**Comment by zeenix** [comment]
> Hello! If there is something specific that I can do to make it seem more reliable, feel free to let me know.

Not specifically, no. I just wanted to know if you're still around and if there is any issue, you'll have the time to review and merge etc.

> For what it's worth, this project is a small component that hasn't required a lot of maintenance. It is also used by other active projects of mine.

Right, that's very understandable. I'm glad to hear you're still around and available. :+1: 

Having said that, I realized my needs are different. With your library, I still need to have the endianness in the type itself. That means, any of my type keeping `ByteOrdered` inside it, has to have a generic on it. In my case, that becomes an long chain. :disappointed: 

I need something more like:

```rust
enum ByteOrder {
    Little(byteorder::LE),
    Big(byteorder::BE),
}

impl ByteOrder {
    // Same API as byteorder::ByteOrder
}
```

**Comment by Enet4** [comment]
> With your library, I still need to have the endianness in the type itself. That means, any of my type keeping `ByteOrdered` inside it, has to have a generic on it. In my case, that becomes an long chain. :disappointed: 
> 

That is not quite true! `Endianness` implements `Endian`, so you should be able to fix the parameter type E to `Endianness`.

```rust
let endianness = Endianness::Little;
let reader = ByteOrdered::<_, Endianness>::runtime(source, endianness);
```

This one can be used in contexts where monomorphisation isn't possible (although it might negatively affect performance due to the extra branching).

**Comment by zeenix** [comment]
> That is not quite true! `Endianness` implements `Endian`, so you should be able to fix the parameter type E to `Endianness`.

Ah, I misunderstood then. 

> This one can be used in contexts where monomorphisation isn't possible (although it might negatively affect performance due to the extra branching).

Right. I think I'll use `Endianness` directly through `Endian`. That way at least there is no dynamic dispatch and hopefully compiler can optimize away the match branching, if I'm very lucky. :)
